import fs from"node:fs/promises";
const read=p=>fs.readFile(p,"utf8");
const [html,css,app,measurement,serverText,gradle,manifest,activity,pkgText,guideEnText,guideThText,signedReleaseWorkflow,gitignore]=await Promise.all(["web/index.html","web/src/styles.css","web/src/app.mjs","web/src/measurement.mjs","web/server-directory.json","app/build.gradle.kts","app/src/main/AndroidManifest.xml","app/src/main/java/com/aistudio/zipspeed/zskt/MainActivity.java","package.json","web/i18n/guide.en.json","web/i18n/guide.th.json",".github/workflows/signed-release.yml",".gitignore"].map(read));
const pkg=JSON.parse(pkgText),directory=JSON.parse(serverText);
for(const old of["index.html","src/app.mjs","src/styles.css","app/applet","app/src/main/assets/index.html"]){try{await fs.access(old);throw new Error("Legacy active source still exists: "+old)}catch(e){if(e.message?.startsWith("Legacy"))throw e}}
if(pkg.version!=="85.0.0"||pkg.zipspeed?.versionCode!==85)throw new Error("Version drift");
if(pkg.zipspeed?.packageId!=="com.aistudio.zipspeed.zskt")throw new Error("Package drift");
if(!gradle.includes('applicationId = "com.aistudio.zipspeed.zskt"')||!gradle.includes("versionCodeFromPackage")||!gradle.includes("versionNameFromPackage")||!gradle.includes("providers.fileContents(packageJsonFile).asText"))throw new Error("Gradle identity/version source invalid or untracked");if(!["ZIPSPEED_KEYSTORE_FILE","ZIPSPEED_KEYSTORE_PASSWORD","ZIPSPEED_KEY_ALIAS","ZIPSPEED_KEY_PASSWORD"].every(x=>gradle.includes(x))||!gradle.includes("releaseSigningReady"))throw new Error("Release signing contract missing");
const signedReleaseSecrets=["ZIPSPEED_KEYSTORE_BASE64","ZIPSPEED_KEYSTORE_PASSWORD","ZIPSPEED_KEY_ALIAS","ZIPSPEED_KEY_PASSWORD"];
if(!signedReleaseWorkflow.includes("workflow_dispatch:")||/^\s*push:/m.test(signedReleaseWorkflow)||/^\s*pull_request:/m.test(signedReleaseWorkflow))throw new Error("Signed release workflow must remain manual-only");
if(!signedReleaseSecrets.every(name=>signedReleaseWorkflow.includes(`secrets.${name}`)))throw new Error("Signed release GitHub secret contract missing");
if(!signedReleaseWorkflow.includes("jarsigner -verify")||!signedReleaseWorkflow.includes("upload-certificate-sha256.txt")||!signedReleaseWorkflow.includes("aab-signer-certificate-sha256.txt")||!signedReleaseWorkflow.includes("keytool -printcert -jarfile")||!signedReleaseWorkflow.includes("cmp -s signed-release-evidence/upload-certificate-sha256.txt signed-release-evidence/aab-signer-certificate-sha256.txt")||!signedReleaseWorkflow.includes("if: always()")||!signedReleaseWorkflow.includes("rm -rf .signing"))throw new Error("Signed release verification/certificate-match/cleanup guard missing");
if(!["*.jks","*.keystore","*.p12","*.pfx",".signing/"].every(rule=>gitignore.includes(rule)))throw new Error("Signing material ignore rules incomplete");
if(!manifest.includes('android:label="ZIPSPEED by AnakinYoo"')||!manifest.includes('android:usesCleartextTraffic="false"'))throw new Error("Manifest hardening/brand missing");
if(!manifest.includes('android:icon="@mipmap/ic_launcher"')||!manifest.includes('android:roundIcon="@mipmap/ic_launcher"')||!manifest.includes('android:theme="@style/Theme.Zipspeed.Launcher"'))throw new Error("Android launcher/splash branding not wired");
const [brandSvg,baseTheme,splashTheme31,launcherIcon]=await Promise.all(["web/assets/zipspeed-mark.svg","app/src/main/res/values/styles.xml","app/src/main/res/values-v31/styles.xml","app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"].map(read));
if(!html.includes('href="./assets/zipspeed-mark.svg?v=85"')||!brandSvg.includes("#3B82F6"))throw new Error("Web brand mark/cache revision missing");
if(!baseTheme.includes("Theme.Zipspeed.Launcher")||!baseTheme.includes("@drawable/zipspeed_splash")||!splashTheme31.includes("windowSplashScreenAnimatedIcon")||!launcherIcon.includes("<adaptive-icon"))throw new Error("Native splash/adaptive icon resources incomplete");
if(!activity.includes("onPageCommitVisible")||!activity.includes("hideStartupSplashIfAppPage")||!activity.includes("onPageFinished"))throw new Error("Startup splash must hide on first visible WebView commit with page-finished fallback");
if(!html.includes('meta name="zipspeed-version" content="__ZIPSPEED_VERSION__"')||!app.includes('meta[name="zipspeed-version"]')||!gradle.includes('replace("__ZIPSPEED_VERSION__", versionNameFromPackage)'))throw new Error("Android bundled version metadata embedding missing");
if(!activity.includes("zipspeedStopForLifecycle")||!activity.includes("MIXED_CONTENT_NEVER_ALLOW"))throw new Error("Android lifecycle/security hook missing");
if((html.match(/id="goButton"/g)||[]).length!==1)throw new Error("GO control must be unique");if(!html.includes('role="tablist"')||!html.includes('role="tabpanel"')||!html.includes('aria-live="polite"')||!html.includes('tabindex="-1"')||!app.includes("ArrowRight")||!app.includes("activateTab"))throw new Error("Accessibility semantics missing");
if(!html.includes('href="./privacy.html"'))throw new Error("In-app privacy link missing");
const guideEn=JSON.parse(guideEnText),guideTh=JSON.parse(guideThText),requiredGuideSections=["getting-started","main-features","permissions","errors","privacy-security","support","accessibility"];
if(!html.includes('id="userGuide"')||!html.includes('id="guideTitle"')||!html.includes('id="guideContent"'))throw new Error("In-app user guide shell missing");
if(!app.includes("async function fetchGuide")||!app.includes('fetchGuide("en")')||!app.includes("loadGuide()"))throw new Error("Guide locale loading or English fallback missing");
for(const [locale,guide] of [["en",guideEn],["th",guideTh]]){if(!guide?.title||!Array.isArray(guide.sections))throw new Error("Guide "+locale+" invalid");const ids=guide.sections.map(x=>x.id);if(requiredGuideSections.some(id=>!ids.includes(id)))throw new Error("Guide "+locale+" missing required section");}

if(!html.includes('id="gaugeMetricLabel"')||!app.includes('gaugeDownload:"ดาวน์โหลด"')||!app.includes('gaugeUpload:"อัปโหลด"'))throw new Error("Gauge Download/Upload phase label missing");
if(!["phaseServerDirectory","phaseServerHealth","phaseMetadata","phaseIdleLatency","phaseDownloadLoaded","phaseUploadLoaded","phaseTimeout"].every(k=>app.includes(k)))throw new Error("Localized measurement phase keys missing");
for(const raw of ['phase(t("failed")+" • server directory")','phase(t("running")+" • server health")','phase(t("running")+" • metadata")','phase(t("running")+" • idle latency")','phase(t("running")+" • download + loaded latency")','phase(t("running")+" • upload + loaded latency")'])if(app.includes(raw))throw new Error("Raw English measurement phase leaked: "+raw);

const privacy=await read("web/privacy.html");if(!privacy.includes("Privacy Policy")||!privacy.includes("Cloudflare")||!privacy.includes("Retention and deletion"))throw new Error("Privacy policy content incomplete");if(!privacy.includes("version 85.0.0")||privacy.includes("version 84.0.0"))throw new Error("Bundled privacy version drift");
for(const tab of["speed","video","status","map","history","settings","adfree"])if(!html.includes(`id="${tab}"`))throw new Error("Missing tab "+tab);
for(const id of["downLoadedLatencyValue","upLoadedLatencyValue","serverValue","serverHealthValue","serverSetting","payloadValue","latencyGraph","monitorButton","monitorIntervalSetting","monitorLog"])if(!html.includes(`id="${id}"`))throw new Error("Missing rebuilt measurement control "+id);
if(!html.includes('id="appVersion"')||!app.includes('fetch("./version.json"'))throw new Error("Runtime version display missing");
if(!app.includes('fetch("./server-directory.json"')||!app.includes("normalizeHistoryEntry")||!app.includes("selectBestServerHealth")||!app.includes("refreshServerHealth")||!app.includes("measureRamp")||!app.includes("runTimeoutTimer")||!app.includes("serverHealthGeneration")||!app.includes("monitorProbe")||!app.includes("monitorTransition")||!app.includes("addLatencySample")||!app.includes("measureUnderLoad")||!app.includes("download-loaded")||!app.includes("upload-loaded"))throw new Error("Loaded-latency/server-directory flow missing");
if(!app.includes("HEALTH_CHECK_TIMEOUT_MS=5000")||!app.includes("HEALTH_CHECK_ATTEMPTS=2")||!app.includes("for(let attempt=0;attempt<HEALTH_CHECK_ATTEMPTS;attempt++)"))throw new Error("Server health retry hardening missing");
if(!Array.isArray(directory.servers)||!directory.servers.some(s=>s.enabled&&s.baseUrl==="https://speed.cloudflare.com"&&s.selection==="anycast-auto"))throw new Error("Verified measurement server missing");
if(!measurement.includes("finishDurationMs:1000")||!measurement.includes("downloadPlanBytes")||!measurement.includes("uploadPlanBytes"))throw new Error("Adaptive standard profile missing");
const speedStart=html.indexOf('<section id="speed"'),speedEnd=html.indexOf('<section id="video"'),speedPanel=speedStart>=0&&speedEnd>speedStart?html.slice(speedStart,speedEnd):"";if(!speedPanel.includes('class="primary-metrics"')||!["downloadValue","uploadValue","latencyValue","jitterValue"].every(id=>speedPanel.includes(`id="${id}"`)))throw new Error("Download/Upload/Ping/Jitter must remain on the main Speed panel");if(!app.includes("smoothGaugeStep")||!measurement.includes("export function smoothGaugeStep")||!app.includes("r.body?.getReader")||!app.includes("calculateMbps(received,performance.now()-start)"))throw new Error("Real-progress smooth gauge flow missing");
if(!app.includes("for(let attempt=0;attempt<3;attempt++)")||!app.includes('fetch("./version.json",{cache:"no-store"})')||!app.includes('$("appVersion").textContent="v--"'))throw new Error("Bundled version retry/fallback missing");
if(/Math\.random\s*\(/.test(app+measurement))throw new Error("Random runtime data forbidden");
if(/packetLoss|packet_loss|packetLossPct/i.test(app+measurement))throw new Error("Unmeasured packet loss forbidden");
if(!html.includes("HTTP probe ≠ packet loss"))throw new Error("Probe disclaimer missing");
if(!css.includes("--blue:#3B82F6")||!/@media\(max-width:(?:3[0-8]0)px\)/.test(css)||!css.includes("prefers-reduced-motion"))throw new Error("Responsive visual system missing");
if(!app.includes("navigator.share")||!app.includes("localStorage"))throw new Error("Share/history flow missing");
console.log("AUDIT PASS — single-source ZIPSPEED v85 + native branding + loaded latency");
