import http from"node:http";import fs from"node:fs/promises";import path from"node:path";import{fileURLToPath}from"node:url";
const repo=path.dirname(fileURLToPath(import.meta.url)),root=path.join(repo,"web"),port=Number(process.env.DEFAULT_APP_PORT||process.env.PORT||3000);
const mime={".html":"text/html; charset=utf-8",".mjs":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".json":"application/json; charset=utf-8"};
function safe(p){const rel=decodeURIComponent(p==="/"?"/index.html":p),candidate=path.normalize(path.join(root,rel)),r=path.relative(root,candidate);return r.startsWith("..")||path.isAbsolute(r)?null:candidate}
const server=http.createServer(async(req,res)=>{res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("Permissions-Policy","geolocation=(), camera=(), microphone=()");res.setHeader("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://speed.cloudflare.com; img-src 'self' data:; object-src 'none'; base-uri 'none'");
if(!["GET","HEAD"].includes(req.method||"GET")){res.writeHead(405,{Allow:"GET, HEAD"});return res.end("Method Not Allowed")}
const u=new URL(req.url||"/","http://localhost");if(u.pathname==="/health"){res.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-store"});return res.end('{"status":"ok"}')}
if(u.pathname==="/version.json"){const p=JSON.parse(await fs.readFile(path.join(repo,"package.json"),"utf8"));res.writeHead(200,{"Content-Type":"application/json","Cache-Control":"no-store"});return res.end(JSON.stringify({version:p.version,versionCode:p.zipspeed.versionCode}))}
const f=safe(u.pathname);if(!f){res.writeHead(403);return res.end("Forbidden")}try{const data=await fs.readFile(f);res.writeHead(200,{"Content-Type":mime[path.extname(f)]||"application/octet-stream","Cache-Control":"no-store"});return req.method==="HEAD"?res.end():res.end(data)}catch{res.writeHead(404);res.end("Not Found")}});
server.listen(port,"0.0.0.0",()=>console.log("ZIPSPEED server listening on :"+port));
