import{TEST_PROFILES,CONNECTION_MODES,calculateMbps,summarizeLatency,summarizeBandwidthStages,shouldStopRamp,splitTransferBytes,speedFraction,parseTraceText,parseProviderMeta,monitorTransition,normalizeHistoryEntry,selectBestServerHealth,validateServerDirectory,videoSuitability}from"./measurement.mjs";
const $=id=>document.getElementById(id);
const HISTORY_KEY="zipspeed_history_v72",MONITOR_KEY="zipspeed_monitor_events_v72";
let controller=null,running=false,runTimedOut=false,runTimeoutTimer=null,runRequestTimeoutMs=30000,lastResult=null,servers=[],activeServer=null,serverHealth=[],serverHealthGeneration=0,graphSamples=[],monitorTimer=null,monitorRunning=false,monitorRequestController=null,monitorState={failures:0,down:false},monitorDisplay={kind:"stopped",latency:null};
const state={profile:localStorage.getItem("zipspeed_profile")||"quick",connection:localStorage.getItem("zipspeed_connection")||"single",lang:localStorage.getItem("zipspeed_lang")||"th",server:localStorage.getItem("zipspeed_server")||"auto",monitorInterval:Number(localStorage.getItem("zipspeed_monitor_interval")||5000)};
const text={
th:{ready:"พร้อมทดสอบด้วยข้อมูลจริง",running:"กำลังวัด",stop:"STOP",go:"GO",failed:"ทดสอบไม่สำเร็จ",map:"Cloudflare เลือก Edge ด้วย Anycast/BGP อัตโนมัติ แอปจึงแสดงรหัส Edge/ประเทศที่รายงานจริงและไม่สร้างพิกัดศูนย์ข้อมูลเอง",tabSpeed:"ความเร็ว",tabVideo:"วิดีโอ",tabStatus:"สถานะ",tabMap:"แผนที่",tabHistory:"ประวัติ",tabSettings:"ตั้งค่า",tabAdfree:"ไม่มีโฆษณา",download:"ดาวน์โหลด",upload:"อัปโหลด",idleLatency:"ค่าหน่วงขณะว่าง",idleJitter:"จิตเตอร์ขณะว่าง",downLoadedLatency:"ค่าหน่วงระหว่างดาวน์โหลด",downLoadedJitter:"จิตเตอร์ระหว่างดาวน์โหลด",upLoadedLatency:"ค่าหน่วงระหว่างอัปโหลด",upLoadedJitter:"จิตเตอร์ระหว่างอัปโหลด",httpProbe:"HTTP probe",payloadRequested:"Payload สำหรับการวัด",quickProfile:"Quick (≈4 MiB)",standardProfile:"Standard adaptive (≤122 MiB)",latencyGraph:"ตัวอย่างค่าหน่วงแบบสด",share:"แชร์ผลลัพธ์",videoEstimate:"ประเมินวิดีโอ",videoNote:"คำนวณจาก Download ที่วัดได้ ไม่ใช่การเล่นวิดีโอจริง",videoThreshold:"เกณฑ์อ้างอิง",clientArea:"พื้นที่ผู้ใช้",measuredAt:"เวลาที่วัด",server:"เซิร์ฟเวอร์",routing:"การเลือก Edge",serverHealth:"สุขภาพเซิร์ฟเวอร์",healthReady:"พร้อม",healthFailed:"ใช้ไม่ได้",healthChecking:"กำลังตรวจ",verifiedLocation:"ข้อมูล Edge ที่ตรวจสอบได้",clear:"ล้าง",testProfile:"รูปแบบการทดสอบ",connections:"การเชื่อมต่อ",serverSetting:"เซิร์ฟเวอร์ทดสอบ",language:"ภาษา",privacyPolicy:"นโยบายความเป็นส่วนตัว",privacyOpen:"เปิดอ่าน",monitorStatusLabel:"มอนิเตอร์",monitorForeground:"ทำงานเฉพาะตอนเปิดแอป",monitorControl:"การเฝ้าดู",monitorInterval:"ช่วงตรวจ",monitorLog:"บันทึกเหตุการณ์",monitorStart:"เริ่ม",monitorStop:"หยุด",monitorStopped:"หยุดอยู่",monitorOk:"ปกติ",monitorDown:"ขัดข้อง",monitorRetry:"กำลังยืนยันปัญหา",monitorWait:"รอ Speed Test จบ",incident:"ขัดข้อง",recovery:"กลับมาใช้งานได้",adfreeBody:"เวอร์ชันทดสอบนี้ยังไม่มี Ads หรือ Billing dependency จึงไม่จำลองสถานะ VIP หรือการชำระเงิน"},
en:{ready:"Ready for a real-data test",running:"Measuring",stop:"STOP",go:"GO",failed:"Test failed",map:"Cloudflare selects the edge automatically using Anycast/BGP. ZIPSPEED shows the reported edge/country and does not invent datacenter coordinates.",tabSpeed:"Speed",tabVideo:"Video",tabStatus:"Status",tabMap:"Map",tabHistory:"History",tabSettings:"Settings",tabAdfree:"Ad-free",download:"Download",upload:"Upload",idleLatency:"Idle latency",idleJitter:"Idle jitter",downLoadedLatency:"Download loaded latency",downLoadedJitter:"Download loaded jitter",upLoadedLatency:"Upload loaded latency",upLoadedJitter:"Upload loaded jitter",httpProbe:"HTTP probe",payloadRequested:"Measurement payload",quickProfile:"Quick (≈4 MiB)",standardProfile:"Standard adaptive (≤122 MiB)",latencyGraph:"Live latency samples",share:"Share result",videoEstimate:"Video estimate",videoNote:"Calculated from measured download speed; this is not a playback test.",videoThreshold:"Reference",clientArea:"Client area",measuredAt:"Measured at",server:"Server",routing:"Edge selection",serverHealth:"Server health",healthReady:"Ready",healthFailed:"Unavailable",healthChecking:"Checking",verifiedLocation:"Verified edge information",clear:"Clear",testProfile:"Test profile",connections:"Connections",serverSetting:"Test server",language:"Language",privacyPolicy:"Privacy policy",privacyOpen:"Open",monitorStatusLabel:"Monitor",monitorForeground:"Runs only while the app is open",monitorControl:"Monitoring",monitorInterval:"Monitor interval",monitorLog:"Monitor log",monitorStart:"Start",monitorStop:"Stop",monitorStopped:"Stopped",monitorOk:"Healthy",monitorDown:"Down",monitorRetry:"Confirming issue",monitorWait:"Wait for speed test",incident:"Incident",recovery:"Recovery",adfreeBody:"This test build has no Ads or Billing dependency, so it does not simulate VIP status or payments."}
};
function t(k){return text[state.lang]?.[k]??text.th[k]??k}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function loadVersion(){try{const r=await fetch("./version.json",{cache:"no-store"});if(!r.ok)throw 0;const v=await r.json();$("appVersion").textContent="v"+v.version}catch{$("appVersion").textContent="v--"}}
async function loadServers(){try{const r=await fetch("./server-directory.json",{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);servers=validateServerDirectory(await r.json());if(!servers.length)throw new Error("No enabled server");activeServer=state.server==="auto"?servers[0]:servers.find(s=>s.id===state.server)||servers[0];renderServerOptions();renderServerStatus();refreshServerHealth()}catch{servers=[];serverHealth=[];activeServer=null;renderServerOptions();renderServerStatus();phase(t("failed")+" • server directory")}}
async function probeServerHealth(server,parentSignal=null){const local=new AbortController(),onAbort=()=>local.abort(),timer=setTimeout(()=>local.abort(),2500),start=performance.now();if(parentSignal?.aborted)local.abort();else parentSignal?.addEventListener("abort",onAbort,{once:true});try{const r=await fetch(server.baseUrl+"/__down?bytes=0&health=1",{cache:"no-store",signal:local.signal});if(!r.ok)throw new Error("HTTP "+r.status);return{id:server.id,ok:true,latencyMs:performance.now()-start}}catch{return{id:server.id,ok:false,latencyMs:null}}finally{clearTimeout(timer);parentSignal?.removeEventListener("abort",onAbort)}}
async function refreshServerHealth(signal=null){if(!servers.length)return null;const generation=++serverHealthGeneration,healthEl=$("serverHealthValue");if(healthEl)healthEl.textContent=t("healthChecking");const results=await Promise.all(servers.map(server=>probeServerHealth(server,signal)));if(signal?.aborted||generation!==serverHealthGeneration)return activeServer;serverHealth=results;if(state.server==="auto"){const best=selectBestServerHealth(serverHealth);activeServer=best?servers.find(s=>s.id===best.id)||null:null}else{const selected=servers.find(s=>s.id===state.server)||null,health=selected?serverHealth.find(x=>x.id===selected.id):null;activeServer=health?.ok?selected:null}renderServerStatus();return activeServer}
function renderServerOptions(){const select=$("serverSetting");if(!select)return;select.innerHTML=['<option value="auto">Auto</option>',...servers.map(s=>`<option value="${s.id}">${s.name}</option>`)].join("");select.value=state.server==="auto"||servers.some(s=>s.id===state.server)?state.server:"auto"}
function renderServerStatus(){if($("serverValue"))$("serverValue").textContent=activeServer?.name||"--";if($("routingValue"))$("routingValue").textContent=activeServer?.selection==="anycast-auto"?"Anycast / BGP":"--";const health=$("serverHealthValue");if(health){const h=activeServer?serverHealth.find(x=>x.id===activeServer.id):null;health.textContent=h?.ok?`${t("healthReady")} • ${h.latencyMs.toFixed(1)} ms`:(serverHealth.length?t("healthFailed"):"--")}}
function setNeedle(v){const finite=Number.isFinite(v),deg=-118+236*speedFraction(v),live=$("liveValue");$("needle").style.transform=`translateX(-50%) rotate(${deg}deg)`;live.textContent=finite?v.toFixed(v<100?1:0):"--";live.classList.toggle("placeholder",!finite)}
function setMetric(id,v,digits=1){$(id).textContent=Number.isFinite(v)?v.toFixed(digits):"--"}
function phase(s){$("phaseText").textContent=s}
function formatNumber(v,digits=1){return Number.isFinite(v)?v.toFixed(digits):"--"}
function renderLatencyGraph(){const line=$("latencyGraphLine"),meta=$("latencyGraphMeta");if(!line||!meta)return;const values=graphSamples.filter(Number.isFinite).slice(-40);meta.textContent=`${values.length} samples`;if(!values.length){line.setAttribute("points","");return}const max=Math.max(...values,1),min=Math.min(...values,0),range=Math.max(1,max-min);const points=values.map((v,i)=>{const x=values.length===1?150:(i/(values.length-1))*296+2;const y=96-((v-min)/range)*92;return `${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");line.setAttribute("points",points)}
function addLatencySample(v){if(!Number.isFinite(v))return;graphSamples.push(v);if(graphSamples.length>40)graphSamples.shift();renderLatencyGraph()}
function resetLatencyGraph(){graphSamples=[];renderLatencyGraph()}
function monitorEvents(){try{const v=JSON.parse(localStorage.getItem(MONITOR_KEY)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function saveMonitorEvent(type,latencyMs=null){const next=[{type,timestamp:new Date().toISOString(),latencyMs:Number.isFinite(latencyMs)?latencyMs:null},...monitorEvents()].slice(0,50);localStorage.setItem(MONITOR_KEY,JSON.stringify(next));renderMonitorLog()}
function renderMonitorLog(){const list=$("monitorLog");if(!list)return;const events=monitorEvents();list.innerHTML=events.length?events.map(e=>`<article class="status-card"><span>${e.type==="incident"?t("incident"):t("recovery")}<small>${new Date(e.timestamp).toLocaleString()}</small></span><strong>${Number.isFinite(e.latencyMs)?e.latencyMs.toFixed(1)+" ms":"--"}</strong></article>`).join(""):'<p class="history-empty">--</p>'}
function renderMonitor(){const status=$("monitorStatus"),button=$("monitorButton");if(!status||!button)return;button.textContent=monitorRunning?t("monitorStop"):t("monitorStart");if(monitorDisplay.kind==="ok")status.textContent=`${t("monitorOk")} • ${formatNumber(monitorDisplay.latency)} ms`;else if(monitorDisplay.kind==="down")status.textContent=t("monitorDown");else if(monitorDisplay.kind==="retry")status.textContent=`${t("monitorRetry")} ${monitorState.failures}/2`;else if(monitorDisplay.kind==="wait")status.textContent=t("monitorWait");else status.textContent=t("monitorStopped")}
function stopMonitor(){monitorRunning=false;if(monitorTimer){clearTimeout(monitorTimer);monitorTimer=null}monitorRequestController?.abort();monitorRequestController=null;monitorState={failures:0,down:false};monitorDisplay={kind:"stopped",latency:null};renderMonitor()}
async function monitorProbe(){if(!monitorRunning)return;if(!activeServer){await loadServers();if(!activeServer){monitorDisplay={kind:"down",latency:null};renderMonitor();monitorTimer=setTimeout(monitorProbe,state.monitorInterval);return}}monitorRequestController=new AbortController();const timeout=setTimeout(()=>monitorRequestController?.abort(),4000),start=performance.now();try{const r=await fetch(endpoint()+"/__down?bytes=0&monitor=1",{cache:"no-store",signal:monitorRequestController.signal});if(!r.ok)throw new Error("HTTP "+r.status);const elapsed=performance.now()-start,next=monitorTransition(monitorState,true,2);monitorState={failures:next.failures,down:next.down};if(next.event==="recovery")saveMonitorEvent("recovery",elapsed);monitorDisplay={kind:"ok",latency:elapsed}}catch{if(!monitorRunning)return;const next=monitorTransition(monitorState,false,2);monitorState={failures:next.failures,down:next.down};if(next.event==="incident")saveMonitorEvent("incident");monitorDisplay={kind:next.down?"down":"retry",latency:null}}finally{clearTimeout(timeout);monitorRequestController=null;renderMonitor();if(monitorRunning)monitorTimer=setTimeout(monitorProbe,state.monitorInterval)}}
function toggleMonitor(){if(monitorRunning){stopMonitor();return}if(running){monitorDisplay={kind:"wait",latency:null};renderMonitor();return}monitorRunning=true;monitorState={failures:0,down:false};monitorDisplay={kind:"retry",latency:null};renderMonitor();monitorProbe()}
function resetResult(){for(const id of["downloadValue","uploadValue","latencyValue","jitterValue","downLoadedLatencyValue","downLoadedJitterValue","upLoadedLatencyValue","upLoadedJitterValue","probeValue","payloadValue"])$(id).textContent="--";resetLatencyGraph();setNeedle(null);$("shareButton").disabled=true}
function setMeasurementSettingsDisabled(disabled){for(const id of["profileSetting","connectionSetting","serverSetting"]){const el=$(id);if(el)el.disabled=disabled}}
async function timedFetch(url,opts={},timeoutMs=runRequestTimeoutMs){const local=new AbortController(),parent=controller?.signal;let timedOut=false;const onAbort=()=>local.abort();if(parent?.aborted)local.abort();else parent?.addEventListener("abort",onAbort,{once:true});const timer=setTimeout(()=>{timedOut=true;local.abort()},timeoutMs),start=performance.now();try{const r=await fetch(url,{...opts,signal:local.signal,cache:"no-store"}),elapsed=performance.now()-start;if(!r.ok)throw new Error("HTTP "+r.status);return{r,elapsed}}catch(e){if(timedOut){const err=new Error("Request timeout");err.name="TimeoutError";throw err}throw e}finally{clearTimeout(timer);parent?.removeEventListener("abort",onAbort)}}
function endpoint(){if(!activeServer)throw new Error("No measurement server");return activeServer.baseUrl}
async function metadata(){try{const {r}=await timedFetch(endpoint()+"/cdn-cgi/trace");return parseProviderMeta(parseTraceText(await r.text()))}catch(e){if(e?.name==="AbortError")throw e;return parseProviderMeta({})}}
async function probes(count,tag="idle",onSample=()=>{}){const values=[];let failed=0;for(let i=0;i<count;i++){try{const {elapsed}=await timedFetch(endpoint()+`/__down?bytes=0&phase=${tag}&n=${i}`);values.push(elapsed);onSample(elapsed)}catch(e){if(e?.name==="AbortError")throw e;failed++}}return{...summarizeLatency(values),values,failed,total:count}}
async function download(bytes,streams){const parts=splitTransferBytes(bytes,streams),start=performance.now();const jobs=parts.map((size,i)=>timedFetch(endpoint()+`/__down?bytes=${size}&stream=${i}`).then(async({r})=>{await r.arrayBuffer();return size}));const done=await Promise.all(jobs),durationMs=performance.now()-start,totalBytes=done.reduce((a,b)=>a+b,0);return{speed:calculateMbps(totalBytes,durationMs),durationMs,bytes:totalBytes}}
async function upload(bytes,streams){const parts=splitTransferBytes(bytes,streams),start=performance.now();const jobs=parts.map((size,i)=>timedFetch(endpoint()+`/__up?stream=${i}`,{method:"POST",headers:{"Content-Type":"application/octet-stream"},body:new Uint8Array(size)}).then(()=>size));const done=await Promise.all(jobs),durationMs=performance.now()-start,totalBytes=done.reduce((a,b)=>a+b,0);return{speed:calculateMbps(totalBytes,durationMs),durationMs,bytes:totalBytes}}
async function measureUnderLoad(transfer,intervalMs,tag,onSample=()=>{},loadedMinDurationMs=0){let active=true;const values=[];let failed=0;const sampler=(async()=>{let n=0;while(active){try{const {elapsed}=await timedFetch(endpoint()+`/__down?bytes=0&phase=${tag}&n=${n++}`);values.push(elapsed);onSample(elapsed)}catch(e){if(e?.name==="AbortError"){active=false;break}failed++}if(active)await sleep(intervalMs)}})();try{const transferResult=await transfer(),eligible=!Number.isFinite(loadedMinDurationMs)||loadedMinDurationMs<=0||transferResult.durationMs>=loadedMinDurationMs,summary=eligible?summarizeLatency(values):{latency:null,jitter:null,samples:0};return{speed:transferResult.speed,durationMs:transferResult.durationMs,bytes:transferResult.bytes,...summary,values:eligible?values:[],failed}}finally{active=false;await sampler}}
async function measureRamp(direction,profile,streams,onSample=()=>{}){const plan=direction==="download"?profile.downloadPlanBytes:profile.uploadPlanBytes,stages=[],allLatency=[];let failed=0;for(let i=0;i<plan.length;i++){phase(t("running")+` • ${direction} ${i+1}/${plan.length}`);const transfer=direction==="download"?()=>download(plan[i],streams):()=>upload(plan[i],streams);const stage=await measureUnderLoad(transfer,profile.loadedProbeIntervalMs,`${direction}-loaded-${i}`,onSample,profile.loadedMinDurationMs);stages.push(stage);allLatency.push(...stage.values);failed+=stage.failed;if(shouldStopRamp(stage.durationMs,profile.finishDurationMs))break}const bw=summarizeBandwidthStages(stages,0.9,profile.bandwidthMinDurationMs),lat=summarizeLatency(allLatency);return{speed:bw.speed,bytes:stages.reduce((sum,s)=>sum+(s.bytes||0),0),stages:bw.stages,latency:lat.latency,jitter:lat.jitter,values:allLatency,failed}}
function renderMeta(m,stamp){$("ipValue").textContent=m.clientIp?m.clientIp+(m.ipVersion?` (${m.ipVersion})`:""):"--";$("ispValue").textContent=m.isp||"--";$("edgeValue").textContent=m.edge||"--";$("areaValue").textContent=m.clientArea||"--";$("timeValue").textContent=stamp?new Date(stamp).toLocaleString():"--";$("mapMessage").textContent=t("map");renderServerStatus()}
function renderVideo(d){const list=videoSuitability(d),known=Number.isFinite(d);$("videoHeadline").textContent=known?`${d.toFixed(1)} Mbps`:"--";$("videoList").innerHTML=list.map(x=>{const stateClass=!known?"video-unknown":x.suitable?"video-ready":"video-fail",status=!known?"--":x.suitable?(state.lang==="th"?"พร้อมใช้งาน":"Ready"):(state.lang==="th"?"ไม่ผ่าน":"Below target");return `<article class="status-card video-card ${stateClass}"><span>${x.label}<small>${t("videoThreshold")} ${x.threshold} Mbps</small></span><strong>${status}</strong></article>`}).join("")}
function history(){try{const raw=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");return Array.isArray(raw)?raw.map(normalizeHistoryEntry):[]}catch{return[]}}
function saveHistory(r){const next=[r,...history()].slice(0,20);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));renderHistory()}
function renderHistory(){const h=history();$("historyList").innerHTML=h.length?h.map(r=>`<article class="metric-card history-card"><header class="history-head"><strong>${r.timestamp?new Date(r.timestamp).toLocaleString():"--"}</strong><span>${r.profile||"--"} • ${r.connection||"--"}</span></header><div class="history-grid"><div><b>${formatNumber(r.downloadMbps)}</b><small>Down Mbps</small></div><div><b>${formatNumber(r.uploadMbps)}</b><small>Up Mbps</small></div><div><b>${formatNumber(r.idleLatencyMs)}</b><small>Idle ms</small></div><div><b>${formatNumber(r.downloadLoadedLatencyMs)}</b><small>Loaded ↓ ms</small></div></div></article>`).join(""):'<p class="history-empty">--</p>'}
async function runTest(){
  if(running){controller?.abort();return}
  if(monitorRunning)stopMonitor();
  running=true;runTimedOut=false;controller=new AbortController();setMeasurementSettingsDisabled(true);resetResult();$("goButton").textContent=t("stop");
  const profile=TEST_PROFILES[state.profile]||TEST_PROFILES.quick;
  runRequestTimeoutMs=profile.requestTimeoutMs||30000;
  runTimeoutTimer=setTimeout(()=>{runTimedOut=true;controller?.abort()},profile.totalTimeoutMs||90000);
  try{
    if(!servers.length)await loadServers();
    phase(t("running")+" • server health");
    await refreshServerHealth(controller.signal);
    if(controller.signal.aborted){const e=new Error("Aborted");e.name="AbortError";throw e}
    if(!activeServer)throw new Error("No healthy measurement server");
    const streams=(CONNECTION_MODES[state.connection]||CONNECTION_MODES.single).streams;
    phase(t("running")+" • metadata");
    const meta=await metadata();
    phase(t("running")+" • idle latency");
    const idle=await probes(profile.probes,"idle",addLatencySample);
    setMetric("latencyValue",idle.latency);setMetric("jitterValue",idle.jitter);$("probeValue").textContent=`${idle.failed}/${idle.total}`;
    phase(t("running")+" • download + loaded latency");
    const down=profile.adaptive?await measureRamp("download",profile,streams,addLatencySample):await measureUnderLoad(()=>download(profile.downloadBytes,streams),profile.loadedProbeIntervalMs,"download-loaded",addLatencySample,250);
    setMetric("downloadValue",down.speed);setNeedle(down.speed);setMetric("downLoadedLatencyValue",down.latency);setMetric("downLoadedJitterValue",down.jitter);
    phase(t("running")+" • upload + loaded latency");
    const up=profile.adaptive?await measureRamp("upload",profile,streams,addLatencySample):await measureUnderLoad(()=>upload(profile.uploadBytes,streams),profile.loadedProbeIntervalMs,"upload-loaded",addLatencySample,250);
    setMetric("uploadValue",up.speed);setMetric("upLoadedLatencyValue",up.latency);setMetric("upLoadedJitterValue",up.jitter);
    const payloadBytes=(down.bytes||profile.downloadBytes||0)+(up.bytes||profile.uploadBytes||0);$("payloadValue").textContent=(payloadBytes/1048576).toFixed(1);
    const stamp=new Date().toISOString();
    lastResult={timestamp:stamp,downloadMbps:down.speed,uploadMbps:up.speed,idleLatencyMs:idle.latency??0,idleJitterMs:idle.jitter??0,downloadLoadedLatencyMs:down.latency,downloadLoadedJitterMs:down.jitter,uploadLoadedLatencyMs:up.latency,uploadLoadedJitterMs:up.jitter,payloadBytes,downloadStages:down.stages??1,uploadStages:up.stages??1,httpProbeFailed:idle.failed,httpProbeTotal:idle.total,profile:state.profile,connection:state.connection,serverId:activeServer.id};
    renderMeta(meta,stamp);renderVideo(down.speed);saveHistory(lastResult);$("shareButton").disabled=false;phase(t("ready"))
  }catch(e){
    if(e?.name==="AbortError")phase(runTimedOut?t("failed")+" • timeout":t("ready"));
    else phase(t("failed")+" • "+(e?.message||"Error"))
  }finally{
    if(runTimeoutTimer){clearTimeout(runTimeoutTimer);runTimeoutTimer=null}
    running=false;controller=null;runTimedOut=false;setMeasurementSettingsDisabled(false);$("goButton").textContent=t("go")
  }
}
function setLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(text[state.lang]?.[key])el.textContent=text[state.lang][key]});phase(running?t("running"):t("ready"));$("goButton").textContent=running?t("stop"):t("go");$("mapMessage").textContent=t("map");renderVideo(lastResult?.downloadMbps??null);renderMonitor();renderMonitorLog()}
function activateTab(button,{focus=false}={}){
  document.querySelectorAll(".tab").forEach(x=>{x.classList.remove("active");x.setAttribute("aria-selected","false");x.tabIndex=-1});
  document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));
  button.classList.add("active");button.setAttribute("aria-selected","true");button.tabIndex=0;$(button.dataset.tab).classList.add("active");
  button.scrollIntoView({block:"nearest",inline:"center"});
  if(focus)button.focus({preventScroll:true});
}
function initTabs(){
  const tabs=[...document.querySelectorAll(".tab")];
  tabs.forEach((b,index)=>{
    b.addEventListener("click",()=>activateTab(b));
    b.addEventListener("keydown",e=>{
      let next=index;
      if(e.key==="ArrowRight")next=(index+1)%tabs.length;
      else if(e.key==="ArrowLeft")next=(index-1+tabs.length)%tabs.length;
      else if(e.key==="Home")next=0;
      else if(e.key==="End")next=tabs.length-1;
      else return;
      e.preventDefault();activateTab(tabs[next],{focus:true});
    });
  });
}
$("goButton").addEventListener("click",runTest);
$("shareButton").addEventListener("click",async()=>{if(!lastResult)return;const loaded=Number.isFinite(lastResult.downloadLoadedLatencyMs)?` / loaded ↓ ${lastResult.downloadLoadedLatencyMs.toFixed(1)} ms`:"";const s=`ZIPSPEED — ↓ ${lastResult.downloadMbps.toFixed(1)} Mbps / ↑ ${lastResult.uploadMbps.toFixed(1)} Mbps / idle ${lastResult.idleLatencyMs.toFixed(1)} ms${loaded}`;if(navigator.share)await navigator.share({title:"ZIPSPEED by AnakinYoo",text:s});else await navigator.clipboard.writeText(s)});
$("clearHistoryButton").addEventListener("click",()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()});
$("profileSetting").value=state.profile;$("connectionSetting").value=state.connection;$("languageSetting").value=state.lang;$("monitorIntervalSetting").value=String([5000,10000,30000].includes(state.monitorInterval)?state.monitorInterval:5000);
$("profileSetting").addEventListener("change",e=>{state.profile=e.target.value;localStorage.setItem("zipspeed_profile",state.profile)});
$("connectionSetting").addEventListener("change",e=>{state.connection=e.target.value;localStorage.setItem("zipspeed_connection",state.connection)});
$("monitorButton").addEventListener("click",toggleMonitor);
$("clearMonitorLogButton").addEventListener("click",()=>{localStorage.removeItem(MONITOR_KEY);renderMonitorLog()});
$("monitorIntervalSetting").addEventListener("change",e=>{state.monitorInterval=Number(e.target.value)||5000;localStorage.setItem("zipspeed_monitor_interval",String(state.monitorInterval));if(monitorRunning){if(monitorTimer)clearTimeout(monitorTimer);monitorTimer=setTimeout(monitorProbe,state.monitorInterval)}});
$("serverSetting").addEventListener("change",async e=>{state.server=e.target.value;localStorage.setItem("zipspeed_server",state.server);activeServer=state.server==="auto"?servers[0]:servers.find(s=>s.id===state.server)||null;renderServerStatus();await refreshServerHealth()});
$("languageSetting").addEventListener("change",e=>{state.lang=e.target.value;localStorage.setItem("zipspeed_lang",state.lang);setLanguage()});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){controller?.abort();if(monitorRunning)stopMonitor()}});window.zipspeedStopForLifecycle=()=>{controller?.abort();stopMonitor()};
initTabs();renderHistory();renderMonitorLog();renderVideo(null);setLanguage();loadVersion();loadServers();
