import{TEST_PROFILES,CONNECTION_MODES,calculateMbps,summarizeLatency,splitTransferBytes,speedFraction,parseTraceText,parseProviderMeta,normalizeHistoryEntry,validateServerDirectory,videoSuitability}from"./measurement.mjs";
const $=id=>document.getElementById(id);
const HISTORY_KEY="zipspeed_history_v72";
let controller=null,running=false,lastResult=null,servers=[],activeServer=null,graphSamples=[];
const state={profile:localStorage.getItem("zipspeed_profile")||"quick",connection:localStorage.getItem("zipspeed_connection")||"single",lang:localStorage.getItem("zipspeed_lang")||"th",server:localStorage.getItem("zipspeed_server")||"auto"};
const text={
th:{ready:"พร้อมทดสอบด้วยข้อมูลจริง",running:"กำลังวัด",stop:"STOP",go:"GO",failed:"ทดสอบไม่สำเร็จ",map:"Cloudflare เลือก Edge ด้วย Anycast/BGP อัตโนมัติ แอปจึงแสดงรหัส Edge/ประเทศที่รายงานจริงและไม่สร้างพิกัดศูนย์ข้อมูลเอง",tabSpeed:"ความเร็ว",tabVideo:"วิดีโอ",tabStatus:"สถานะ",tabMap:"แผนที่",tabHistory:"ประวัติ",tabSettings:"ตั้งค่า",tabAdfree:"ไม่มีโฆษณา",download:"ดาวน์โหลด",upload:"อัปโหลด",idleLatency:"ค่าหน่วงขณะว่าง",idleJitter:"จิตเตอร์ขณะว่าง",downLoadedLatency:"ค่าหน่วงระหว่างดาวน์โหลด",downLoadedJitter:"จิตเตอร์ระหว่างดาวน์โหลด",upLoadedLatency:"ค่าหน่วงระหว่างอัปโหลด",upLoadedJitter:"จิตเตอร์ระหว่างอัปโหลด",httpProbe:"HTTP probe",payloadRequested:"Payload ที่ร้องขอ",latencyGraph:"ตัวอย่างค่าหน่วงแบบสด",share:"แชร์ผลลัพธ์",videoEstimate:"ประเมินวิดีโอ",videoNote:"คำนวณจาก Download ที่วัดได้ ไม่ใช่การเล่นวิดีโอจริง",clientArea:"พื้นที่ผู้ใช้",measuredAt:"เวลาที่วัด",server:"เซิร์ฟเวอร์",routing:"การเลือก Edge",verifiedLocation:"ข้อมูล Edge ที่ตรวจสอบได้",clear:"ล้าง",testProfile:"รูปแบบการทดสอบ",connections:"การเชื่อมต่อ",serverSetting:"เซิร์ฟเวอร์ทดสอบ",language:"ภาษา",adfreeBody:"เวอร์ชันทดสอบนี้ยังไม่มี Ads หรือ Billing dependency จึงไม่จำลองสถานะ VIP หรือการชำระเงิน"},
en:{ready:"Ready for a real-data test",running:"Measuring",stop:"STOP",go:"GO",failed:"Test failed",map:"Cloudflare selects the edge automatically using Anycast/BGP. ZIPSPEED shows the reported edge/country and does not invent datacenter coordinates.",tabSpeed:"Speed",tabVideo:"Video",tabStatus:"Status",tabMap:"Map",tabHistory:"History",tabSettings:"Settings",tabAdfree:"Ad-free",download:"Download",upload:"Upload",idleLatency:"Idle latency",idleJitter:"Idle jitter",downLoadedLatency:"Download loaded latency",downLoadedJitter:"Download loaded jitter",upLoadedLatency:"Upload loaded latency",upLoadedJitter:"Upload loaded jitter",httpProbe:"HTTP probe",payloadRequested:"Payload requested",latencyGraph:"Live latency samples",share:"Share result",videoEstimate:"Video estimate",videoNote:"Calculated from measured download speed; this is not a playback test.",clientArea:"Client area",measuredAt:"Measured at",server:"Server",routing:"Edge selection",verifiedLocation:"Verified edge information",clear:"Clear",testProfile:"Test profile",connections:"Connections",serverSetting:"Test server",language:"Language",adfreeBody:"This test build has no Ads or Billing dependency, so it does not simulate VIP status or payments."}
};
function t(k){return text[state.lang]?.[k]??text.th[k]??k}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function loadVersion(){try{const r=await fetch("./version.json",{cache:"no-store"});if(!r.ok)throw 0;const v=await r.json();$("appVersion").textContent="v"+v.version}catch{$("appVersion").textContent="v--"}}
async function loadServers(){try{const r=await fetch("./server-directory.json",{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);servers=validateServerDirectory(await r.json());if(!servers.length)throw new Error("No enabled server");activeServer=state.server==="auto"?servers[0]:servers.find(s=>s.id===state.server)||servers[0];renderServerOptions();renderServerStatus()}catch{servers=[];activeServer=null;renderServerOptions();renderServerStatus();phase(t("failed")+" • server directory")}}
function renderServerOptions(){const select=$("serverSetting");if(!select)return;select.innerHTML=['<option value="auto">Auto</option>',...servers.map(s=>`<option value="${s.id}">${s.name}</option>`)].join("");select.value=state.server==="auto"||servers.some(s=>s.id===state.server)?state.server:"auto"}
function renderServerStatus(){if($("serverValue"))$("serverValue").textContent=activeServer?.name||"--";if($("routingValue"))$("routingValue").textContent=activeServer?.selection==="anycast-auto"?"Anycast / BGP":"--"}
function setNeedle(v){const deg=-118+236*speedFraction(v);$("needle").style.transform=`translateX(-50%) rotate(${deg}deg)`;$("liveValue").textContent=Number.isFinite(v)?v.toFixed(v<100?1:0):"--"}
function setMetric(id,v,digits=1){$(id).textContent=Number.isFinite(v)?v.toFixed(digits):"--"}
function phase(s){$("phaseText").textContent=s}
function formatNumber(v,digits=1){return Number.isFinite(v)?v.toFixed(digits):"--"}
function renderLatencyGraph(){const line=$("latencyGraphLine"),meta=$("latencyGraphMeta");if(!line||!meta)return;const values=graphSamples.filter(Number.isFinite).slice(-40);meta.textContent=`${values.length} samples`;if(!values.length){line.setAttribute("points","");return}const max=Math.max(...values,1),min=Math.min(...values,0),range=Math.max(1,max-min);const points=values.map((v,i)=>{const x=values.length===1?150:(i/(values.length-1))*296+2;const y=96-((v-min)/range)*92;return `${x.toFixed(1)},${y.toFixed(1)}`}).join(" ");line.setAttribute("points",points)}
function addLatencySample(v){if(!Number.isFinite(v))return;graphSamples.push(v);if(graphSamples.length>40)graphSamples.shift();renderLatencyGraph()}
function resetLatencyGraph(){graphSamples=[];renderLatencyGraph()}
function resetResult(){for(const id of["downloadValue","uploadValue","latencyValue","jitterValue","downLoadedLatencyValue","downLoadedJitterValue","upLoadedLatencyValue","upLoadedJitterValue","probeValue","payloadValue"])$(id).textContent="--";resetLatencyGraph();setNeedle(null);$("shareButton").disabled=true}
async function timedFetch(url,opts={}){const start=performance.now();const r=await fetch(url,{...opts,signal:controller.signal,cache:"no-store"});const elapsed=performance.now()-start;if(!r.ok)throw new Error("HTTP "+r.status);return{r,elapsed}}
function endpoint(){if(!activeServer)throw new Error("No measurement server");return activeServer.baseUrl}
async function metadata(){try{const {r}=await timedFetch(endpoint()+"/cdn-cgi/trace");return parseProviderMeta(parseTraceText(await r.text()))}catch(e){if(e?.name==="AbortError")throw e;return parseProviderMeta({})}}
async function probes(count,tag="idle",onSample=()=>{}){const values=[];let failed=0;for(let i=0;i<count;i++){try{const {elapsed}=await timedFetch(endpoint()+`/__down?bytes=0&phase=${tag}&n=${i}`);values.push(elapsed);onSample(elapsed)}catch(e){if(e?.name==="AbortError")throw e;failed++}}return{...summarizeLatency(values),values,failed,total:count}}
async function download(bytes,streams){const parts=splitTransferBytes(bytes,streams);const start=performance.now();const jobs=parts.map((size,i)=>timedFetch(endpoint()+`/__down?bytes=${size}&stream=${i}`).then(async({r})=>{await r.arrayBuffer();return size}));const done=await Promise.all(jobs);return calculateMbps(done.reduce((a,b)=>a+b,0),performance.now()-start)}
async function upload(bytes,streams){const parts=splitTransferBytes(bytes,streams);const start=performance.now();const jobs=parts.map((size,i)=>timedFetch(endpoint()+`/__up?stream=${i}`,{method:"POST",headers:{"Content-Type":"application/octet-stream"},body:new Uint8Array(size)}).then(()=>size));const done=await Promise.all(jobs);return calculateMbps(done.reduce((a,b)=>a+b,0),performance.now()-start)}
async function measureUnderLoad(transfer,intervalMs,tag,onSample=()=>{}){let active=true;const values=[];let failed=0;const sampler=(async()=>{let n=0;while(active){try{const {elapsed}=await timedFetch(endpoint()+`/__down?bytes=0&phase=${tag}&n=${n++}`);values.push(elapsed);onSample(elapsed)}catch(e){if(e?.name==="AbortError"){active=false;break}failed++}if(active)await sleep(intervalMs)}})();try{const speed=await transfer();return{speed,...summarizeLatency(values),values,failed}}finally{active=false;await sampler}}
function renderMeta(m,stamp){$("ipValue").textContent=m.clientIp?m.clientIp+(m.ipVersion?` (${m.ipVersion})`:""):"--";$("ispValue").textContent=m.isp||"--";$("edgeValue").textContent=m.edge||"--";$("areaValue").textContent=m.clientArea||"--";$("timeValue").textContent=stamp?new Date(stamp).toLocaleString():"--";$("mapMessage").textContent=t("map");renderServerStatus()}
function renderVideo(d){const list=videoSuitability(d);$("videoHeadline").textContent=Number.isFinite(d)?`${d.toFixed(1)} Mbps`:"--";$("videoList").innerHTML=list.map(x=>`<article class="status-card"><span>${x.label}<small>threshold ${x.threshold} Mbps</small></span><strong>${Number.isFinite(d)?(x.suitable?(state.lang==="th"?"พร้อมใช้งาน":"Ready"):(state.lang==="th"?"ไม่ผ่าน":"Below target")):"--"}</strong></article>`).join("")}
function history(){try{const raw=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");return Array.isArray(raw)?raw.map(normalizeHistoryEntry):[]}catch{return[]}}
function saveHistory(r){const next=[r,...history()].slice(0,20);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));renderHistory()}
function renderHistory(){const h=history();$("historyList").innerHTML=h.length?h.map(r=>`<article class="metric-card history-card"><strong>${r.timestamp?new Date(r.timestamp).toLocaleString():"--"}</strong><div class="history-grid"><div><b>${formatNumber(r.downloadMbps)}</b><small>Down Mbps</small></div><div><b>${formatNumber(r.uploadMbps)}</b><small>Up Mbps</small></div><div><b>${formatNumber(r.idleLatencyMs)}</b><small>Idle ms</small></div><div><b>${formatNumber(r.downloadLoadedLatencyMs)}</b><small>Loaded ↓ ms</small></div></div></article>`).join(""):'<p class="history-empty">--</p>'}
async function runTest(){if(running){controller?.abort();return}if(!activeServer){await loadServers();if(!activeServer){phase(t("failed")+" • server");return}}running=true;controller=new AbortController();resetResult();$("goButton").textContent=t("stop");phase(t("running")+" • metadata");try{const profile=TEST_PROFILES[state.profile]||TEST_PROFILES.quick;const streams=(CONNECTION_MODES[state.connection]||CONNECTION_MODES.single).streams;const meta=await metadata();phase(t("running")+" • idle latency");const idle=await probes(profile.probes,"idle",addLatencySample);setMetric("latencyValue",idle.latency);setMetric("jitterValue",idle.jitter);$("probeValue").textContent=`${idle.failed}/${idle.total}`;phase(t("running")+" • download + loaded latency");const down=await measureUnderLoad(()=>download(profile.downloadBytes,streams),profile.loadedProbeIntervalMs,"download-loaded",addLatencySample);setMetric("downloadValue",down.speed);setNeedle(down.speed);setMetric("downLoadedLatencyValue",down.latency);setMetric("downLoadedJitterValue",down.jitter);phase(t("running")+" • upload + loaded latency");const up=await measureUnderLoad(()=>upload(profile.uploadBytes,streams),profile.loadedProbeIntervalMs,"upload-loaded",addLatencySample);setMetric("uploadValue",up.speed);setMetric("upLoadedLatencyValue",up.latency);setMetric("upLoadedJitterValue",up.jitter);const payloadBytes=profile.downloadBytes+profile.uploadBytes;$("payloadValue").textContent=(payloadBytes/1048576).toFixed(1);const stamp=new Date().toISOString();lastResult={timestamp:stamp,downloadMbps:down.speed,uploadMbps:up.speed,idleLatencyMs:idle.latency??0,idleJitterMs:idle.jitter??0,downloadLoadedLatencyMs:down.latency,downloadLoadedJitterMs:down.jitter,uploadLoadedLatencyMs:up.latency,uploadLoadedJitterMs:up.jitter,payloadBytes,httpProbeFailed:idle.failed,httpProbeTotal:idle.total,profile:state.profile,connection:state.connection,serverId:activeServer.id};renderMeta(meta,stamp);renderVideo(down.speed);saveHistory(lastResult);$("shareButton").disabled=false;phase(t("ready"))}catch(e){if(e?.name==="AbortError")phase(t("ready"));else phase(t("failed")+" • "+(e?.message||"Error"))}finally{running=false;controller=null;$("goButton").textContent=t("go")}}
function setLanguage(){document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(text[state.lang]?.[key])el.textContent=text[state.lang][key]});phase(t("ready"));$("goButton").textContent=running?t("stop"):t("go");$("mapMessage").textContent=t("map");renderVideo(lastResult?.downloadMbps??null)}
function initTabs(){document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")}))}
$("goButton").addEventListener("click",runTest);
$("shareButton").addEventListener("click",async()=>{if(!lastResult)return;const loaded=Number.isFinite(lastResult.downloadLoadedLatencyMs)?` / loaded ↓ ${lastResult.downloadLoadedLatencyMs.toFixed(1)} ms`:"";const s=`ZIPSPEED — ↓ ${lastResult.downloadMbps.toFixed(1)} Mbps / ↑ ${lastResult.uploadMbps.toFixed(1)} Mbps / idle ${lastResult.idleLatencyMs.toFixed(1)} ms${loaded}`;if(navigator.share)await navigator.share({title:"ZIPSPEED by AnakinYoo",text:s});else await navigator.clipboard.writeText(s)});
$("clearHistoryButton").addEventListener("click",()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()});
$("profileSetting").value=state.profile;$("connectionSetting").value=state.connection;$("languageSetting").value=state.lang;
$("profileSetting").addEventListener("change",e=>{state.profile=e.target.value;localStorage.setItem("zipspeed_profile",state.profile)});
$("connectionSetting").addEventListener("change",e=>{state.connection=e.target.value;localStorage.setItem("zipspeed_connection",state.connection)});
$("serverSetting").addEventListener("change",e=>{state.server=e.target.value;localStorage.setItem("zipspeed_server",state.server);activeServer=state.server==="auto"?servers[0]:servers.find(s=>s.id===state.server)||servers[0];renderServerStatus()});
$("languageSetting").addEventListener("change",e=>{state.lang=e.target.value;localStorage.setItem("zipspeed_lang",state.lang);setLanguage()});
window.zipspeedStopForLifecycle=()=>controller?.abort();
initTabs();renderHistory();renderVideo(null);setLanguage();loadVersion();loadServers();
