import{TEST_PROFILES,CONNECTION_MODES,calculateMbps,median,latencyJitter,splitTransferBytes,speedFraction,parseProviderMeta,videoSuitability}from"./measurement.mjs";
const $=id=>document.getElementById(id);
const ENDPOINT="https://speed.cloudflare.com";
const HISTORY_KEY="zipspeed_history_v72";
let controller=null,running=false,lastResult=null;
const state={profile:localStorage.getItem("zipspeed_profile")||"quick",connection:localStorage.getItem("zipspeed_connection")||"single",lang:localStorage.getItem("zipspeed_lang")||"th"};
const text={th:{ready:"พร้อมทดสอบด้วยข้อมูลจริง",running:"กำลังวัด",stop:"STOP",go:"GO",failed:"ทดสอบไม่สำเร็จ",probe:"HTTP probe ล้มเหลว",map:"ยังไม่มีพิกัดที่ตรวจสอบได้ จึงไม่แสดงตำแหน่งสมมติ"},en:{ready:"Ready for a real-data test",running:"Measuring",stop:"STOP",go:"GO",failed:"Test failed",probe:"HTTP probe failed",map:"No verified coordinates are available, so no location is invented."}};
function t(k){return text[state.lang]?.[k]??text.th[k]??k}
async function loadVersion(){try{const r=await fetch("./version.json",{cache:"no-store"});if(!r.ok)throw 0;const v=await r.json();$("appVersion").textContent="v"+v.version}catch{$("appVersion").textContent="v--"}}
function setNeedle(v){const deg=-118+236*speedFraction(v);$("needle").style.transform=`translateX(-50%) rotate(${deg}deg)`; $("liveValue").textContent=Number.isFinite(v)?v.toFixed(v<100?1:0):"--"}
function setMetric(id,v,digits=1){$(id).textContent=Number.isFinite(v)?v.toFixed(digits):"--"}
function phase(s){$("phaseText").textContent=s}
function resetResult(){for(const id of["downloadValue","uploadValue","latencyValue","jitterValue","probeValue"])$(id).textContent="--";setNeedle(null);$("shareButton").disabled=true}
async function timedFetch(url,opts={}){const start=performance.now();const r=await fetch(url,{...opts,signal:controller.signal,cache:"no-store"});const elapsed=performance.now()-start;if(!r.ok)throw new Error("HTTP "+r.status);return{r,elapsed}}
async function metadata(){try{const {r}=await timedFetch(ENDPOINT+"/meta");return parseProviderMeta(await r.json())}catch{return parseProviderMeta({})}}
async function probes(count){const values=[];let failed=0;for(let i=0;i<count;i++){try{const {elapsed}=await timedFetch(ENDPOINT+"/__down?bytes=0&n="+i);values.push(elapsed)}catch(e){if(e?.name==="AbortError")throw e;failed++}}return{latency:median(values),jitter:latencyJitter(values),failed,total:count}}
async function download(bytes,streams){const parts=splitTransferBytes(bytes,streams);const start=performance.now();const jobs=parts.map((size,i)=>timedFetch(ENDPOINT+`/__down?bytes=${size}&stream=${i}`).then(async({r})=>{await r.arrayBuffer();return size}));const done=await Promise.all(jobs);return calculateMbps(done.reduce((a,b)=>a+b,0),performance.now()-start)}
async function upload(bytes,streams){const parts=splitTransferBytes(bytes,streams);const start=performance.now();const jobs=parts.map((size,i)=>timedFetch(ENDPOINT+`/__up?stream=${i}`,{method:"POST",headers:{"Content-Type":"application/octet-stream"},body:new Uint8Array(size)}).then(()=>size));const done=await Promise.all(jobs);return calculateMbps(done.reduce((a,b)=>a+b,0),performance.now()-start)}
function renderMeta(m,stamp){$("ipValue").textContent=m.clientIp?m.clientIp+(m.ipVersion?` (${m.ipVersion})`:""):"--";$("ispValue").textContent=m.isp||"--";$("edgeValue").textContent=m.edge||"--";$("areaValue").textContent=m.clientArea||"--";$("timeValue").textContent=stamp?new Date(stamp).toLocaleString():"--";$("mapMessage").textContent=t("map")}
function renderVideo(d){const list=videoSuitability(d);$("videoHeadline").textContent=Number.isFinite(d)?`${d.toFixed(1)} Mbps`:"--";$("videoList").innerHTML=list.map(x=>`<article class="status-card"><span>${x.label}<small>threshold ${x.threshold} Mbps</small></span><strong>${Number.isFinite(d)?(x.suitable?"พร้อมใช้งาน":"ไม่ผ่าน"):"--"}</strong></article>`).join("")}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]")}catch{return[]}}
function saveHistory(r){const next=[r,...history()].slice(0,20);localStorage.setItem(HISTORY_KEY,JSON.stringify(next));renderHistory()}
function renderHistory(){const h=history();$("historyList").innerHTML=h.length?h.map(r=>`<article class="metric-card history-card"><strong>${new Date(r.timestamp).toLocaleString()}</strong><div class="history-grid"><div><b>${r.downloadMbps.toFixed(1)}</b><small>Down Mbps</small></div><div><b>${r.uploadMbps.toFixed(1)}</b><small>Up Mbps</small></div><div><b>${r.latencyMs.toFixed(1)}</b><small>Latency ms</small></div><div><b>${r.jitterMs.toFixed(1)}</b><small>Jitter ms</small></div></div></article>`).join(""):'<p class="history-empty">--</p>'}
async function runTest(){if(running){controller?.abort();return}running=true;controller=new AbortController();resetResult();$("goButton").textContent=t("stop");phase(t("running")+" • metadata");try{const profile=TEST_PROFILES[state.profile]||TEST_PROFILES.quick;const streams=(CONNECTION_MODES[state.connection]||CONNECTION_MODES.single).streams;const meta=await metadata();phase(t("running")+" • latency");const p=await probes(profile.probes);setMetric("latencyValue",p.latency);setMetric("jitterValue",p.jitter);$("probeValue").textContent=`${p.failed}/${p.total}`;phase(t("running")+" • download");const down=await download(profile.downloadBytes,streams);setMetric("downloadValue",down);setNeedle(down);phase(t("running")+" • upload");const up=await upload(profile.uploadBytes,streams);setMetric("uploadValue",up);const stamp=new Date().toISOString();lastResult={timestamp:stamp,downloadMbps:down,uploadMbps:up,latencyMs:p.latency??0,jitterMs:p.jitter??0,httpProbeFailed:p.failed,httpProbeTotal:p.total,profile:state.profile,connection:state.connection};renderMeta(meta,stamp);renderVideo(down);saveHistory(lastResult);$("shareButton").disabled=false;phase(t("ready"))}catch(e){if(e?.name==="AbortError")phase(t("ready"));else phase(t("failed")+" • "+(e?.message||"Error"))}finally{running=false;controller=null;$("goButton").textContent=t("go")}}
function setLanguage(){document.documentElement.lang=state.lang;phase(t("ready"));$("goButton").textContent=running?t("stop"):t("go");$("mapMessage").textContent=t("map")}
function initTabs(){document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")}))}
$("goButton").addEventListener("click",runTest);
$("shareButton").addEventListener("click",async()=>{if(!lastResult)return;const s=`ZIPSPEED — ↓ ${lastResult.downloadMbps.toFixed(1)} Mbps / ↑ ${lastResult.uploadMbps.toFixed(1)} Mbps / latency ${lastResult.latencyMs.toFixed(1)} ms`;if(navigator.share)await navigator.share({title:"ZIPSPEED by AnakinYoo",text:s});else await navigator.clipboard.writeText(s)});
$("clearHistoryButton").addEventListener("click",()=>{localStorage.removeItem(HISTORY_KEY);renderHistory()});
$("profileSetting").value=state.profile;$("connectionSetting").value=state.connection;$("languageSetting").value=state.lang;
$("profileSetting").addEventListener("change",e=>{state.profile=e.target.value;localStorage.setItem("zipspeed_profile",state.profile)});
$("connectionSetting").addEventListener("change",e=>{state.connection=e.target.value;localStorage.setItem("zipspeed_connection",state.connection)});
$("languageSetting").addEventListener("change",e=>{state.lang=e.target.value;localStorage.setItem("zipspeed_lang",state.lang);setLanguage()});
window.zipspeedStopForLifecycle=()=>controller?.abort();
initTabs();renderHistory();renderVideo(null);setLanguage();loadVersion();
